In [ ]:
#1
import numpy as np
vector = np.arange(10, 50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [ ]:
#2
matrix = np.arange(9).reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [5]:
#3
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [7]:
#4
random_array = np.random.rand(3, 3)
print(random_array) 

[[0.34994736 0.36286837 0.14035277]
 [0.67751826 0.91114566 0.79964655]
 [0.42299412 0.497718   0.95376436]]


In [ ]:
#5
random_array = np.random.randn(10, 10)
min_val = np.min(random_array)
max_val = np.max(random_array)
print("Array:\n", random_array)
print("min:", min_val)
print("max:", max_val)

Array:
 [[ 0.7616295  -0.08379202  0.22469036  1.0385832  -0.47418828 -0.16066894
   0.97206455  0.03409468  0.80591893  1.71773334]
 [ 1.23133237  0.54490215  0.60777574 -0.45199461 -0.68232886 -0.4657835
   0.5074375  -0.02444483  0.18363704 -0.45997031]
 [ 1.90443615 -0.34550371 -1.38281269 -0.76814587 -0.48902088 -0.09722089
   0.65360809 -0.03684423 -0.9522921   0.0559413 ]
 [-0.24889322  1.49840876  0.77340647 -1.25725381 -0.4581308   1.60420884
   0.63241105  0.84174678 -0.01742034  2.03442492]
 [-1.90965671  0.19524789  2.06245471  0.73478395  1.607668    0.39498711
  -0.16932136 -1.46888566  0.56394525 -0.82006507]
 [-0.10609642  0.65832908  1.00189976  1.53294751 -1.46474692 -0.14101952
   1.45118641 -2.03166289  1.1107428   1.00909812]
 [ 0.25975643 -0.6068822  -0.46282076  0.57490656 -1.94902753 -0.6882625
   2.04734445 -0.89118951 -0.58011079  0.72530859]
 [-0.51606737 -1.04729124 -0.50015001 -0.86646727  0.28245743 -1.2630317
  -0.06110325  0.29694569 -2.94501574 -0.09236

In [9]:
#6
random_vector = np.random.rand(30)
mean_value = np.mean(random_vector)
print("Vector:", random_vector)
print("Mean:", mean_value)

Vector: [0.67908758 0.76221113 0.04665073 0.18631848 0.94262645 0.61655911
 0.58230968 0.49603716 0.82370962 0.18928018 0.12915761 0.30861998
 0.10395121 0.09139816 0.86567733 0.29111667 0.42742936 0.68440689
 0.20009938 0.87081537 0.75949092 0.27964453 0.08398465 0.33256298
 0.49794153 0.63634912 0.98066674 0.35473261 0.73461284 0.92633058]
Mean: 0.496125952724647


In [10]:
#7
random_matrix = np.random.rand(5, 5)
normalized_matrix = (random_matrix - np.mean(random_matrix)) / np.std(random_matrix)
print("Original matrix:\n", random_matrix)
print("Normalized matrix:\n", normalized_matrix)


Original matrix:
 [[0.67025464 0.49572053 0.36802828 0.2199874  0.67230467]
 [0.62178496 0.27647996 0.77030544 0.82001794 0.62719059]
 [0.93471044 0.90822165 0.67098666 0.44972027 0.00975969]
 [0.72156689 0.72253572 0.35052641 0.91212549 0.22764908]
 [0.80785602 0.28692271 0.14371198 0.93120151 0.03306288]]
Normalized matrix:
 [[ 0.43658284 -0.17718265 -0.62622436 -1.14682395  0.44379197]
 [ 0.26613469 -0.94816261  0.78842084  0.96323948  0.2851441 ]
 [ 1.36656635  1.27341607  0.43915705 -0.33894688 -1.88610934]
 [ 0.61702717  0.62043415 -0.68777132  1.28714427 -1.11988095]
 [ 0.92047096 -0.91143968 -1.41505359  1.35422687 -1.80416149]]


In [11]:
#8
matrix1 = np.random.rand(5, 3)
matrix2 = np.random.rand(3, 2)
product = np.dot(matrix1, matrix2)
print("Matrix1:\n", matrix1)
print("Matrix2:\n", matrix2)
print("Product:\n", product)


Matrix1:
 [[0.10023814 0.46792562 0.67354869]
 [0.41505572 0.64808683 0.10575265]
 [0.24293077 0.14842841 0.59344834]
 [0.12909948 0.19299071 0.42903679]
 [0.11241366 0.87388288 0.04818664]]
Matrix2:
 [[0.3988896  0.56285785]
 [0.940593   0.06147742]
 [0.18326224 0.20003964]]
Product:
 [[0.60354755 0.21992312]
 [0.79452781 0.2946148 ]
 [0.34526995 0.26457368]
 [0.31164839 0.17035359]
 [0.87563955 0.12663621]]


In [12]:
#9
matrix1 = np.random.rand(3, 3)
matrix2 = np.random.rand(3, 3)
dot_product = np.dot(matrix1, matrix2)
print("Matrix1:\n", matrix1)
print("Matrix2:\n", matrix2)
print("Dpt product:\n", dot_product)

Matrix1:
 [[0.2686736  0.87918205 0.18233631]
 [0.83061581 0.99451992 0.61598103]
 [0.69203908 0.98661266 0.26090237]]
Matrix2:
 [[0.84538036 0.56502431 0.22267895]
 [0.68113107 0.13742055 0.84614605]
 [0.81367414 0.03210061 0.6461169 ]]
Dpt product:
 [[0.97433194 0.2784779  0.92155495]
 [1.88079254 0.62575896 1.42446551]
 [1.4693383  0.53497488 1.15749438]]


In [13]:
#10
matrix = np.random.rand(4, 4)
transpose_matrix = matrix.T
print("Original matrix:\n", matrix)
print("Transposed matrix:\n", transpose_matrix)


Original matrix:
 [[0.22637385 0.09949075 0.33789138 0.59865541]
 [0.19770393 0.93514011 0.86697776 0.22912252]
 [0.89849669 0.36424159 0.23064849 0.02280524]
 [0.48019421 0.02899624 0.21987645 0.76464295]]
Transposed matrix:
 [[0.22637385 0.19770393 0.89849669 0.48019421]
 [0.09949075 0.93514011 0.36424159 0.02899624]
 [0.33789138 0.86697776 0.23064849 0.21987645]
 [0.59865541 0.22912252 0.02280524 0.76464295]]


In [14]:
#11
matrix = np.random.rand(3, 3)
determinant = np.linalg.det(matrix)
print("Matrix:\n", matrix)
print("Determinant:", determinant)


Matrix:
 [[0.50877924 0.7903943  0.05211303]
 [0.17667552 0.21439462 0.75262525]
 [0.15935615 0.51815764 0.21853523]]
Determinant: -0.10730565430274125


In [16]:
#12
A = np.random.rand(3, 4)
B = np.random.rand(4, 3)
product = np.dot(A, B)
print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("Matrix Product (A dot B):\n", product)

Matrix A:
 [[0.6923123  0.91353282 0.81500346 0.01497447]
 [0.68387609 0.08573836 0.66389758 0.88465011]
 [0.28794426 0.81469447 0.13754757 0.1993685 ]]
Matrix B:
 [[0.75241517 0.49659347 0.70193983]
 [0.82829702 0.43319781 0.11923083]
 [0.18441756 0.50884685 0.79709154]
 [0.71942391 0.9952028  0.07584882]]
Matrix Product (A dot B):
 [[1.43865672 1.16915276 1.24565101]
 [1.34444838 1.59497852 1.08654933]
 [1.06025928 0.76431783 0.42401611]]


In [19]:
#13
matrix = np.random.rand(3, 3)
vector = np.random.rand(3, 1)
product = np.dot(matrix, vector)
print("Matrix:\n", matrix)
print("Vector:\n", vector)
print("Matrix-Vector Product:\n", product)

Matrix:
 [[0.6474737  0.4779483  0.04857595]
 [0.56544754 0.23530032 0.37891297]
 [0.28253029 0.16390668 0.25047862]]
Vector:
 [[0.68511154]
 [0.68904534]
 [0.17632721]]
Matrix-Vector Product:
 [[0.78148501]
 [0.61633989]
 [0.35067009]]


In [18]:
#14
A = np.random.rand(3, 3)
b = np.random.rand(3, 1)
x = np.linalg.solve(A, b)
print("Matrix A:\n", A)
print("Vector b:\n", b)
print("Solution x:\n", x)

Matrix A:
 [[0.75613675 0.23528455 0.59927889]
 [0.94422623 0.31893001 0.04860332]
 [0.30243914 0.97182703 0.68004238]]
Vector b:
 [[0.99277792]
 [0.51877443]
 [0.62515817]]
Solution x:
 [[ 0.58213938]
 [-0.25250965]
 [ 1.02124833]]


In [21]:
#15
matrix = np.random.rand(5, 5)
row_sum = np.sum(matrix, axis=1)
column_sum = np.sum(matrix, axis=0)
print("Matrix:\n", matrix)
print("Row-wise sums:", row_sum)
print("Column-wise sums:", column_sum)

Matrix:
 [[0.33906092 0.15775189 0.80232286 0.54591692 0.80887879]
 [0.88733893 0.1408021  0.55693161 0.60865947 0.25933761]
 [0.73852677 0.30523499 0.72731439 0.49708383 0.05058383]
 [0.29762476 0.05011458 0.56300887 0.88769882 0.40484902]
 [0.32288524 0.89355978 0.58257856 0.93032695 0.58156765]]
Row-wise sums: [2.65393138 2.45306971 2.31874381 2.20329604 3.31091818]
Column-wise sums: [2.58543661 1.54746333 3.2321563  3.46968599 2.10521689]
